### PR TITLE
Serving sug

### PR DESCRIPTION
**Pull request by hchidziwi**
Can you review the code?

### CODE REVIEW

**Comment by mayacodes** [comment]
Okay I will review now

**Comment by hchidziwi** [comment]
> Okay I will review now

Okay ... waiting. Thanks!

**Review by mayacodes — COMMENTED** [review]
Is it spicy enough? Do we need to add some chiles?

**Comment by hchidziwi** [comment]
> Is it spicy enough? Do we need to add some chiles?

I added some chiles...can you taste it now?

**Pull request merged**
